services:
  carla-driving-simulator-client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: carla-simulator-client:dev
    container_name: carla-simulator-client-dev
    ports:
      - "3000:3000"    # Frontend
      #- "8000:8000"    # Backend API
      #- "2000-2002:2000-2002"  # CARLA ports
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./reports:/app/reports
    env_file:
      - .env
    environment:
      # Override defaults if .env file doesn't exist
      - DATABASE_URL=${DATABASE_URL:-postgresql://carla_user:carla_password@localhost:5432/carla_simulator}
      - CARLA_HOST=${CARLA_HOST:-localhost}
      - CARLA_PORT=${CARLA_PORT:-2000}
      - WEB_HOST=${WEB_HOST:-0.0.0.0}
      - WEB_PORT=${WEB_PORT:-8000}
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEBUG=${DEBUG:-true}
      - TESTING=${TESTING:-false}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/scenarios"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
    networks:
      - carla-network

  # Optional: PostgreSQL service
  # postgres:
  #   image: postgres:13
  #   container_name: carla-postgres
  #   environment:
  #     POSTGRES_DB: carla_simulator
  #     POSTGRES_USER: carla_user
  #     POSTGRES_PASSWORD: carla_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - carla-network
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "carla_user"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

networks:
  carla-network:
    driver: bridge

# volumes:
#   postgres_data:
