version: '3.8'

services:
  carla-driving-simulator-client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  # Frontend
      - "8000:8000"  # Backend API
      - "2000-2002:2000-2002"  # CARLA ports
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./reports:/app/reports
    environment:
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - REACT_APP_API_URL=http://localhost:8000
      - WDS_SOCKET_HOST=0.0.0.0
      - WDS_SOCKET_PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/scenarios"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s

  # Optional: Add a database service if needed
  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: carla_simulator
  #     POSTGRES_USER: carla_user
  #     POSTGRES_PASSWORD: carla_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: 