global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Carla application metrics
  - job_name: "carla-client"
    static_configs:
      - targets: ["carla-client:8000"]
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: "carla-server"
    static_configs:
      - targets: ["carla-server:2000"]
    scrape_interval: 15s
    metrics_path: /metrics

  # System metrics (CPU, Memory, Disk, Network)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 10s

  # Container metrics (per-container resource usage)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 15s

  # GPU metrics (DGX A100 cluster)
  - job_name: "gpu-exporter"
    static_configs:
      - targets: ["gpu-exporter:9445"]
    scrape_interval: 10s
