# .github/workflows/pull-request-ci.yml
name: Pull Request CI

on:
  pull_request:
    branches: [ master, CI/CD ]

jobs:
  python-ci:
    name: "Test and Build Python Package"
    uses: ./.github/workflows/reusable-python-ci.yml
    secrets: inherit
    with:
      python-version: '3.11'
      upload-coverage: true

  docker-ci:
    name: "Test Docker Build"
    needs: python-ci
    uses: ./.github/workflows/reusable-docker-ci.yml
    with:
      version: ${{ needs.python-ci.outputs.version }}
      publish: false 