# .github/workflows/reusable-docker-ci.yml
name: Reusable Docker CI

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: "The version tag for the Docker image"
      publish:
        required: false
        type: boolean
        description: "Set to true to publish the image to Docker Hub"
        default: false
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

env:
  DOCKER_IMAGE: akshaychikhalkar/carla-driving-simulator-client

jobs:
  build_and_publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: inputs.publish == true
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and (optionally) push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ inputs.publish }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:latest
            ${{ env.DOCKER_IMAGE }}:${{ inputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          platforms: linux/amd64 