# .github/workflows/reusable-release.yml
name: Reusable Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: "The version to publish"
    secrets:
      PYPI_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true

jobs:
  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist/

      - name: Publish to PyPI
        run: |
          python -m pip install --upgrade twine
          python -m twine upload --skip-existing --verbose dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

  github-release:
    name: Create GitHub Release
    needs: pypi-publish
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist/
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ inputs.version }}
          tag_name: v${{ inputs.version }}
          files: |
            dist/*.whl
            dist/*.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 