name: Frontend Tests (Quick)

on:
  # Only trigger on PRs and manual dispatch
  # Production and development builds handle their own testing
  pull_request:
    branches: [ master, develop ]
    paths:
      - 'web/frontend/**'
  workflow_dispatch:

env:
  NODE_VERSION: "18"

jobs:
  test-frontend:
    name: Run frontend tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: web/frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci
        working-directory: web/frontend

      - name: Run frontend tests
        run: npm run test:ci
        working-directory: web/frontend
        env:
          CI: true
          NODE_ENV: test

      - name: Upload frontend test coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: akshaychikhalkar/carla-driving-simulator-client
          flags: frontend
          name: frontend-coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload frontend test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: frontend-test-results
          path: web/frontend/coverage/

  # Quick test summary for frontend-only changes
  test-summary:
    name: Frontend Test Summary
    runs-on: ubuntu-latest
    needs: [test-frontend]
    if: always()
    steps:
      - name: Generate frontend test summary
        run: |
          echo "## Frontend Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ needs.test-frontend.result }}" == "success" ]; then
            echo "✅ **Frontend Tests**: PASSED" >> $GITHUB_STEP_SUMMARY
            echo "🎉 All frontend tests completed successfully!" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Frontend Tests**: FAILED" >> $GITHUB_STEP_SUMMARY
            echo "🔧 Please check the test results above for details." >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📊 **Coverage Report**: Available in the artifacts" >> $GITHUB_STEP_SUMMARY
          echo "📋 **Test Results**: Available in the artifacts" >> $GITHUB_STEP_SUMMARY

      - name: Fail if frontend tests failed
        if: needs.test-frontend.result != 'success'
        run: |
          echo "❌ Frontend tests failed. Please check the test results above."
          exit 1
